In [1]:

import pandas as pd
import numpy as np

In [23]:
dt = pd.read_csv("vehicles.csv", sep=";")  # or '\t' for tab‑separated

In [24]:
print(dt)

    Make,Model,Year,Engine Size (L),Fuel Type,Price
0              Toyota,Corolla,2018,1.8,Petrol,15000
1                 Honda,Civic,2019,2.0,Petrol,17000
2                  Ford,Focus,2017,1.5,Diesel,14000
3             Hyundai,Elantra,2020,2.0,Petrol,18000
4            Chevrolet,Malibu,2016,2.5,Petrol,13500
..                                              ...
145                    BMW,X6,2018,3.0,Petrol,80000
146           Mercedes,GLS400,2019,3.0,Petrol,90000
147                   Audi,Q8,2017,3.0,Petrol,95000
148              Lexus,UX250h,2020,2.0,Hybrid,60000
149              Jeep,Compass,2018,2.0,Diesel,25000

[150 rows x 1 columns]

In [26]:
ct = dt.columns

In [27]:
print(ct)

Index(['Make,Model,Year,Engine Size (L),Fuel Type,Price'], dtype='object')

In [28]:
st=dt.shape

In [29]:
print(st)

(150, 1)

In [30]:
cv=dt.columns.values

In [31]:

print(cv)

['Make,Model,Year,Engine Size (L),Fuel Type,Price']

In [34]:
dt.describe()

       Make,Model,Year,Engine Size (L),Fuel Type,Price
count                                              150
unique                                             150
top               Toyota,Corolla,2018,1.8,Petrol,15000
freq                                                 1

In [35]:

dt.describe(include='all')

       Make,Model,Year,Engine Size (L),Fuel Type,Price
count                                              150
unique                                             150
top               Toyota,Corolla,2018,1.8,Petrol,15000
freq                                                 1

KeyError: "None of [Index(['Model'], dtype='object')] are in the [columns]"